# Generated by Django 5.2 on 2025-04-08 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_itemsdetails_exp_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemsdetails",
            name="exp_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 4, 15, 5, 8, 36, 200658, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Expiration date",
            ),
        ),
    ]
