# Generated by Django 5.2 on 2025-04-08 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_itemsdetails_exp_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemsdetails",
            name="exp_date",
        ),
        migrations.AddField(
            model_name="itemsdetails",
            name="item_expdate",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 4, 15, 5, 13, 36, 964496, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Expiration date",
            ),
        ),
    ]
