# Generated by Django 4.2.20 on 2025-04-11 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_itemsdetails_exp_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fridgecontent',
            old_name='family',
            new_name='family_id',
        ),
        migrations.RenameField(
            model_name='itemsdetails',
            old_name='id',
            new_name='item_id',
        ),
        migrations.RemoveField(
            model_name='itemsdetails',
            name='item_expdate',
        ),
        migrations.AddField(
            model_name='fridgecontent',
            name='item_height',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='fridgecontent',
            name='item_length',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='fridgecontent',
            name='item_width',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='itemsdetails',
            name='dimension_height',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='itemsdetails',
            name='dimension_length',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='itemsdetails',
            name='dimension_width',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.CreateModel(
            name='FridgeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compartment_name', models.CharField(max_length=200)),
                ('compartment_length', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('compartment_width', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('compartment_height', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('family_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FridgeDetails', to='inventory.family')),
            ],
        ),
    ]
