# Generated by Django 4.2.20 on 2025-04-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_family_fridgecontent_family_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FridgeDetails',
            new_name='FridgeDetail',
        ),
    ]
