# Generated by Django 4.2.20 on 2025-04-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_itemsdetails_item_image_itemsdetails_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsdetails',
            name='item_type',
            field=models.CharField(choices=[('Produce', 'Produce'), ('Freezer', 'Freezer'), ('Left Shelves', 'Left Shelves'), ('Middle Shelves', 'Middle Shelves'), ('Right Shelves', 'Right Shelves')], default=True, max_length=30),
        ),
    ]
