# Generated by Django 4.2.20 on 2025-04-14 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_itemsdetails_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='familytag',
            name='Fridge_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.fridgedetail'),
        ),
    ]
