# Generated by Django 5.2 on 2025-04-17 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_familytag_fridge_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="familytag",
            name="Fridge_id",
        ),
    ]
