# Generated by Django 5.2 on 2025-04-17 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_remove_familytag_fridge_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_space",
                    models.DecimalField(decimal_places=2, default=1, max_digits=2),
                ),
                (
                    "leftdoor_space",
                    models.DecimalField(decimal_places=2, default=1, max_digits=2),
                ),
                (
                    "rightdoor_space",
                    models.DecimalField(decimal_places=2, default=1, max_digits=2),
                ),
                (
                    "producebin_space",
                    models.DecimalField(decimal_places=2, default=1, max_digits=2),
                ),
                (
                    "freezer_space",
                    models.DecimalField(decimal_places=2, default=1, max_digits=2),
                ),
                (
                    "family_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile",
                        to="inventory.family",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
