# Generated by Django 4.2.20 on 2025-04-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_family_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='familytag',
            name='limit_ratio',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=3),
        ),
    ]
