# Generated by Django 5.2 on 2025-04-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_familytag_limit_ratio"),
    ]

    operations = [
        migrations.AddField(
            model_name="fridgedetail",
            name="capacity",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="fridgedetail",
            name="current_item_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="itemsdetails",
            name="item_expiration",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="itemsdetails",
            name="item_image",
            field=models.ImageField(default="default.jpeg", upload_to=""),
        ),
        migrations.AlterField(
            model_name="itemsdetails",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("Produce", "Produce"),
                    ("Freezer", "Freezer"),
                    ("Left Shelves", "Left Shelves"),
                    ("Middle Shelves", "Middle Shelves"),
                    ("Right Shelves", "Right Shelves"),
                ],
                default="Produce",
                max_length=30,
            ),
        ),
    ]
