# Generated by Django 5.2 on 2025-04-21 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_fridgedetail_capacity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="family_id",
        ),
    ]
