# Generated by Django 4.2.20 on 2025-04-21 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_userprofile_family_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fridgedetail',
            name='compartment_height',
        ),
        migrations.RemoveField(
            model_name='fridgedetail',
            name='compartment_length',
        ),
        migrations.RemoveField(
            model_name='fridgedetail',
            name='compartment_name',
        ),
        migrations.RemoveField(
            model_name='fridgedetail',
            name='compartment_width',
        ),
        migrations.CreateModel(
            name='CompartmentsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compartment_name', models.CharField(max_length=200)),
                ('compartment_length', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('compartment_width', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('compartment_height', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('family_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CompartmentDetails', to='inventory.family')),
            ],
        ),
    ]
