# Generated by Django 4.2.20 on 2025-04-21 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_remove_fridgedetail_compartment_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compartmentsdetails',
            name='family_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CompartmentsDetails', to='inventory.family'),
        ),
    ]
