# Generated by Django 4.2.20 on 2025-04-21 20:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_compartmentsdetails_family_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compartmentsdetails',
            name='id',
        ),
        migrations.AddField(
            model_name='compartmentsdetails',
            name='compartment_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='fridgecontent',
            name='compartment_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='compartment_details', to='inventory.compartmentsdetails'),
            preserve_default=False,
        ),
    ]
