# Generated by Django 4.2.20 on 2025-04-24 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0020_remove_compartmentsdetails_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgecontent',
            name='family_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridge_contents', to=settings.AUTH_USER_MODEL),
        ),
    ]
