# Generated by Django 5.2 on 2025-04-29 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0022_fridgecontent_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fridgecontent",
            name="location",
            field=models.CharField(default="fridge", max_length=50),
        ),
        migrations.AlterField(
            model_name="familytag",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="FamilyTag",
                to="inventory.family",
            ),
        ),
        migrations.AlterField(
            model_name="familytag",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="FamilyTag",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fridgecontent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="FridgeContent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
