# Generated by Django 5.2 on 2025-04-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0023_fridgecontent_location_alter_familytag_family_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(default="default.jpeg", upload_to=""),
        ),
    ]
