# Generated by Django 5.2 on 2025-04-29 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0024_userprofile_profile_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="user_id",
            new_name="user",
        ),
    ]
