# Generated by Django 5.2 on 2025-05-05 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0029_alter_userprofile_freezer_space_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="freezer_space",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="leftdoor_space",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="producebin_space",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="rightdoor_space",
        ),
    ]
