# Generated by Django 5.2 on 2025-05-05 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0030_remove_userprofile_freezer_space_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="overall_space",
        ),
        migrations.AlterUniqueTogether(
            name="fridgecontent",
            unique_together={
                ("family_id", "compartment_id", "item_id", "expiration_date")
            },
        ),
    ]
